spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softuni_graduation?useSSL=true&createDatabaseIfNotExist=true
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        validator:
          apply_to_ddl: false

    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      springframework:
        session:
          web:
            http:
              SessionRepositoryFilter:
                SESSION_LOGGER=DEBUG: debug
        web: DEBUG

sendgrid:
  apiKey: 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

server:
  port: 8080